class M3Uzi
  class Tag < Item

    attr_reader :name
    attr_accessor :value

    VALID_TAGS = %w{ALLOW-CACHE}

    # Unsupported tags: I-FRAMES-ONLY
    # Autogenerated tags: EXTM3U, VERSION, ENDLIST, BYTERANGE, TARGETDURATION, MEDIA-SEQUENCE, PLAYLIST-TYPE

    def name=(n)
      @name = n.to_s.upcase.gsub("_", "-")
    end

    def format
      string << "#EXT-X-#{name}"
      string << ":#{value}" if value
      string
    end

    def valid?
      case name
      when 'ALLOW-CACHE'
        ['YES','NO'].include?(value)
      else
        true
      end
    end
  end

end
